### PR TITLE
Fixed `registered_commands` namespace

### LINKED ISSUE #4: [Proposition] Namespace organisation
For the sake of readability and organisation I propose to move `registered_commands` to a separate namespace.

`ctr` is a global mod namespace. So it's a bit inconvinient to have a `command-callback` list in the root of that namespace.

My proposition is to move `ctr.registered_commands` into a sub-namespace. Like so: `ctr.NSP.registered_commands`, where NSP may be `storage`, `game`, or `int` (for `internal`).

The issue was raised to discuss the change and so other contributors don't freak out when they see their favourite command register is non-existent.

### PR DESCRIPTION
**Pull request by nitrogenez**
This PR moves `modular_computers.registered_commands` to the `modular_computers.os` namespace. See Issue #4.

### CODE REVIEW

File: init.lua [hunk 1]
```diff
@@ -14,7 +14,7 @@ modular_computers.mod = {}
 modular_computers.mod.name = minetest.get_current_modname()
 modular_computers.mod.path = minetest.get_modpath(modular_computers.mod.name)
 
-modular_computers.registered_commands = {}
+modular_computers.os.registered_commands = {}
```
Comment (y5nw) [inline init.lua]: IMO this can be moved into `src/os/api/cli.lua`, as this is where the command registration handling takes place.

Also, the `modular_computers.os` namespace is defined later in `src/os/init.lua` (and for some reason this is loaded _after_  other `os/` scripts, which needs to be addressed as well).

---

With that proposal, it can be possible to create `register_command` and `registered_commands` together, such as:
```lua
modular_computers.os.register_command, module_computers.os.registered_commands = make_registration()
```
with
```lua
function make_registration()
  local t = {}
  return t, function(k, v) t[k] = v end
end
```

Then such a "registration creator" can be reused for other purposes in the future.

Comment (nitrogenez) [reply init.lua]: That's a little abstract and I don't really see where that could be used, so I don't see any purpose in that.

Comment (y5nw) [reply init.lua]: The suggestions mainly comes from my assumption that it will be possible to (globally) register other things than commands. I personally do not consider the abstraction a problem in itself.

That said, I agree that this is currently not needed.

**Comment by JamesClarke7283** [comment]
I recommend changing the namespace to `modular_computers.internal.command.register([name], [callback])` as specified in issue #4 

Let me know if you have any issue with this.

**Comment by nitrogenez** [comment]
> I recommend changing the namespace to `modular_computers.internal.command.register([name], [callback])` as specified in issue #4 
> 
> Let me know if you have any issue with this.

No issues, will do in an upcoming hour.

**Comment by y5nw** [comment]
Rebase needed.

**Comment by nitrogenez** [comment]
> Rebase needed.

I'm unavailable until Tuesday. Do you have any ideas how to make things work without me?

**Comment by y5nw** [comment]
> > Rebase needed.
> 
> I'm unavailable until Tuesday. Do you have any ideas how to make things work without me?

In that case, I can do the rebase if you want.

---

Edit: while I do support using `luacheck`, I fail to find any polite term to describe the mess caused by reformatting the code in 687efb3.

**Comment by nitrogenez** [comment]
> > > Rebase needed.
> > 
> > I'm unavailable until Tuesday. Do you have any ideas how to make things work without me?
> 
> In that case, I can do the rebase if you want.

Fine. Notify me if you have any questions.
